export default {
    SET_GAME_VIEW: "SET_GAME_VIEW",
    RESET_GAME_VIEW: "RESET_GAME_VIEW",
    SET_PLAYER_STATE: "SET_PLAYER_STATE",
    RESET_PLAYER_STATE: "RESET_PLAYER_STATE",
    SET_PLAYER_SPEED: "SET_PLAYER_SPEED",
    SET_PLAYER_HISTORY_LENGTH: "SET_PLAYER_HISTORY_LENGTH"
};
