export default {
  SET_GAME_VIEW: "SET_GAME_VIEW",
  RESET_GAME_VIEW: "RESET_GAME_VIEW",
  SET_PLAYER_STATE: "SET_PLAYER_STATE",
  RESET_PLAYER_STATE: "RESET_PLAYER_STATE",
  SET_PLAYER_SPEED: "SET_PLAYER_SPEED",
  SET_PLAYER_HISTORY_LENGTH: "SET_PLAYER_HISTORY_LENGTH",
  SET_DISPLAY_COLORS: "SET_DISPLAY_COLORS",
  SET_DISPLAY_OFFSET: "SET_DISPLAY_OFFSET",
  SET_DISPLAY_SCALE: "SET_DISPLAY_SCALE",
  INITIATE_CREATE_FILE: "INITIATE_CREATE_FILE",
  CREATE_FILE: "CREATE_FILE",
  CANCEL_CREATE_FILE: "CANCEL_CREATE_FILE"
};
